import { useState, useEffect } from 'react';
import JSZip from 'jszip';
import { usePipelineStore } from '../store/pipelineStore';
import { apiClient } from '../lib/apiClient';

type ShipItModalProps = {
  isOpen: boolean;
  onClose: () => void;
};

// Safe fallback code if generation fails
const FALLBACK_CODE = `# Forge Pipeline Export
# Generation failed - please try again or check your pipeline configuration

import anthropic

def run_pipeline(user_input: str) -> str:
    """
    Placeholder pipeline - replace with your implementation
    """
    client = anthropic.Anthropic()

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1024,
        messages=[{"role": "user", "content": user_input}]
    )

    return message.content[0].text

if __name__ == "__main__":
    result = run_pipeline("Hello, how can you help?")
    print(result)
`;

export const ShipItModal = ({ isOpen, onClose }: ShipItModalProps) => {
  const { nodes, edges, setIsGeneratingCode } = usePipelineStore();
  const [generatedCode, setGeneratedCode] = useState('');
  const [requiredKeys, setRequiredKeys] = useState<string[]>([]);
  const [apiKeys, setApiKeys] = useState<Record<string, string>>({});
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen) {
      // Reset state when modal opens
      setError(null);
      setGeneratedCode('');
      setRequiredKeys([]);
      setApiKeys({});

      // Only generate if we have nodes
      if (nodes.length > 0) {
        generateCode();
      } else {
        setError('No nodes in pipeline. Create a pipeline first before exporting.');
        setGeneratedCode(FALLBACK_CODE);
      }
    }
    // generateCode is intentionally omitted: including it would re-trigger on every render
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen]);

  const generateCode = async () => {
    setIsLoading(true);
    setIsGeneratingCode(true);
    setError(null); // Reset error state

    try {
      const result: any = await apiClient.generateCode({ nodes, edges });

      // 🛡️ DEFENSIVE GUARDS: Validate API response structure
      if (!result || typeof result !== 'object') {
        throw new Error('Invalid API response: result is not an object');
      }

      // Validate code field
      const code = result.code;
      if (typeof code !== 'string' || code.trim() === '') {
        console.warn('[ShipIt] Invalid code in API response, using fallback');
        setGeneratedCode(FALLBACK_CODE);
      } else {
        setGeneratedCode(code);
      }

      // Validate requiredKeys field
      const keys = result.requiredKeys;
      if (!Array.isArray(keys)) {
        console.warn('[ShipIt] Invalid requiredKeys in API response, using empty array');
        setRequiredKeys([]);
        setApiKeys({});
      } else {
        setRequiredKeys(keys);

        // Initialize API keys object
        const apiKeysObj: Record<string, string> = {};
        keys.forEach((key: string) => {
          if (typeof key === 'string') {
            apiKeysObj[key] = '';
          }
        });
        setApiKeys(apiKeysObj);
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
      console.error('[ShipIt] Failed to generate code:', errorMessage);

      // Set error state for UI
      setError(`Code generation failed: ${errorMessage}`);

      // Use fallback code so modal is still functional
      setGeneratedCode(FALLBACK_CODE);
      setRequiredKeys([]);
      setApiKeys({});
    } finally {
      setIsLoading(false);
      setIsGeneratingCode(false);
    }
  };

  const handleDownload = async () => {
    try {
      const zip = new JSZip();

      // Add the generated code (with safety check)
      const codeToExport = typeof generatedCode === 'string' && generatedCode.trim()
        ? generatedCode
        : FALLBACK_CODE;
      zip.file('pipeline.py', codeToExport);

      // Add .env file with API keys (with safety check)
      const safeApiKeys = typeof apiKeys === 'object' && apiKeys !== null ? apiKeys : {};
      const envContent = Object.entries(safeApiKeys)
        .filter(([key]) => typeof key === 'string')
        .map(([key, value]) => `${key}=${value || 'your-key-here'}`)
        .join('\n');
      zip.file('.env', envContent || '# No API keys required\n');

      // Add requirements.txt
      const requirements = `anthropic
openai
google-generativeai
python-dotenv
requests`;
      zip.file('requirements.txt', requirements);

      // Add README (with safety check for API keys list)
      const apiKeysList = Object.keys(safeApiKeys).length > 0
        ? Object.keys(safeApiKeys).map((key) => `   - ${key}`).join('\n')
        : '   - No API keys required';

      const readme = `# AI Pipeline - Generated by Forge

## Setup

1. Install dependencies:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`

2. Configure your API keys in \`.env\`:
${apiKeysList}

3. Run the pipeline:
   \`\`\`bash
   python pipeline.py
   \`\`\`

## Generated with Forge ⚡
Build multi-LLM pipelines visually and ship them as real code.
`;
      zip.file('README.md', readme);

      // Generate and download the ZIP file
      const content = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'forge-pipeline.zip';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('[ShipIt] Download failed:', err);
      alert('Failed to generate download. Please try again.');
    }
  };

  if (!isOpen) return null;

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0, 0, 0, 0.85)',
        backdropFilter: 'blur(8px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
        padding: '40px',
      }}
      onClick={onClose}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          background: 'var(--bg-panel)',
          border: '1px solid var(--border)',
          borderRadius: '12px',
          width: '100%',
          maxWidth: '1200px',
          height: '80vh',
          display: 'flex',
          overflow: 'hidden',
          boxShadow: '0 20px 60px rgba(0, 0, 0, 0.5)',
        }}
      >
        {/* Left Panel - Code Preview */}
        <div
          style={{
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            borderRight: '1px solid var(--border)',
          }}
        >
          {/* Header */}
          <div
            style={{
              padding: '24px',
              borderBottom: '1px solid var(--border)',
            }}
          >
            <div
              style={{
                fontFamily: 'Syne, sans-serif',
                fontSize: '20px',
                fontWeight: 700,
                display: 'flex',
                alignItems: 'center',
                gap: '10px',
              }}
            >
              <span>🚀</span>
              <span>Generated Pipeline Code</span>
            </div>
            <div
              style={{
                fontSize: '13px',
                color: 'var(--text-muted)',
                marginTop: '4px',
              }}
            >
              Production-ready Python code for your AI pipeline
            </div>
          </div>

          {/* Code Display - Terminal Style */}
          <div
            style={{
              flex: 1,
              overflow: 'auto',
              background: '#0d1117',
              position: 'relative',
            }}
          >
            {isLoading ? (
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  height: '100%',
                  color: '#10b981',
                  flexDirection: 'column',
                  gap: '16px',
                }}
              >
                <div
                  style={{
                    width: '40px',
                    height: '40px',
                    border: '3px solid rgba(16, 185, 129, 0.2)',
                    borderTopColor: '#10b981',
                    borderRadius: '50%',
                    animation: 'spin 1s linear infinite',
                  }}
                />
                <div style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: '13px' }}>
                  $ Compiling pipeline...
                </div>
                <style>
                  {`
                    @keyframes spin {
                      to { transform: rotate(360deg); }
                    }
                  `}
                </style>
              </div>
            ) : error ? (
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  height: '100%',
                  padding: '40px',
                  flexDirection: 'column',
                  gap: '16px',
                }}
              >
                <div style={{ fontSize: '48px' }}>⚠️</div>
                <div
                  style={{
                    fontFamily: 'JetBrains Mono, monospace',
                    fontSize: '14px',
                    color: '#f43f5e',
                    textAlign: 'center',
                    maxWidth: '400px',
                  }}
                >
                  {error}
                </div>
                <div
                  style={{
                    fontFamily: 'JetBrains Mono, monospace',
                    fontSize: '12px',
                    color: '#8b949e',
                    textAlign: 'center',
                  }}
                >
                  Fallback code has been loaded below. You can still download the project.
                </div>
              </div>
            ) : (
              <>
                {/* Terminal Prompt Header */}
                <div
                  style={{
                    padding: '12px 24px',
                    background: '#161b22',
                    borderBottom: '1px solid #30363d',
                    fontFamily: 'JetBrains Mono, monospace',
                    fontSize: '12px',
                    color: '#10b981',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    position: 'sticky',
                    top: 0,
                    zIndex: 1,
                  }}
                >
                  <span style={{ color: '#f59e0b' }}>⚡</span>
                  <span style={{ color: '#8b949e' }}>forge@terminal:</span>
                  <span>~</span>
                  <span style={{ color: '#8b949e' }}>$</span>
                  <span style={{ color: '#58a6ff' }}>python pipeline.py</span>
                </div>
                {/* Code Content */}
                <pre
                  style={{
                    margin: 0,
                    padding: '24px',
                    fontFamily: 'JetBrains Mono, monospace',
                    fontSize: '13px',
                    lineHeight: '1.7',
                    color: '#c9d1d9',
                    whiteSpace: 'pre-wrap',
                    wordBreak: 'break-word',
                    background: 'transparent',
                  }}
                >
                  {typeof generatedCode === 'string' ? generatedCode : FALLBACK_CODE}
                </pre>
              </>
            )}
          </div>
        </div>

        {/* Right Panel - Configuration */}
        <div
          style={{
            width: '380px',
            display: 'flex',
            flexDirection: 'column',
          }}
        >
          {/* Header */}
          <div
            style={{
              padding: '24px',
              borderBottom: '1px solid var(--border)',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
            }}
          >
            <div>
              <div
                style={{
                  fontFamily: 'Syne, sans-serif',
                  fontSize: '18px',
                  fontWeight: 600,
                }}
              >
                Configuration
              </div>
              <div
                style={{
                  fontSize: '12px',
                  color: 'var(--text-muted)',
                  marginTop: '2px',
                }}
              >
                Set up your API keys
              </div>
            </div>
            <button
              onClick={onClose}
              style={{
                background: 'transparent',
                border: 'none',
                color: 'var(--text-muted)',
                cursor: 'pointer',
                fontSize: '24px',
                padding: '4px',
                lineHeight: 1,
              }}
            >
              ×
            </button>
          </div>

          {/* API Keys Form */}
          <div
            style={{
              flex: 1,
              overflowY: 'auto',
              padding: '24px',
              display: 'flex',
              flexDirection: 'column',
              gap: '20px',
            }}
          >
            <div>
              <div
                style={{
                  fontSize: '12px',
                  fontWeight: 600,
                  color: 'var(--text-muted)',
                  marginBottom: '12px',
                  textTransform: 'uppercase',
                  letterSpacing: '0.5px',
                }}
              >
                Required API Keys
              </div>
              {!Array.isArray(requiredKeys) || requiredKeys.length === 0 ? (
                <div
                  style={{
                    fontSize: '13px',
                    color: 'var(--text-muted)',
                    fontStyle: 'italic',
                  }}
                >
                  No API keys required for this pipeline.
                </div>
              ) : (
                requiredKeys.filter((key) => typeof key === 'string').map((key) => (
                  <div key={key} style={{ marginBottom: '16px' }}>
                    <label
                      style={{
                        display: 'block',
                        fontSize: '12px',
                        color: 'var(--text-primary)',
                        marginBottom: '6px',
                        fontFamily: 'JetBrains Mono, monospace',
                      }}
                    >
                      {key}
                    </label>
                    <input
                      type="password"
                      placeholder="Enter your API key..."
                      value={apiKeys[key] || ''}
                      onChange={(e) =>
                        setApiKeys((prev) => ({
                          ...prev,
                          [key]: e.target.value,
                        }))
                      }
                      style={{
                        width: '100%',
                        height: '40px',
                        background: 'var(--bg-card)',
                        border: '1px solid var(--border)',
                        borderRadius: '6px',
                        padding: '0 12px',
                        color: 'var(--text-primary)',
                        fontSize: '13px',
                        fontFamily: 'JetBrains Mono, monospace',
                        outline: 'none',
                      }}
                      onFocus={(e) => {
                        e.target.style.borderColor = 'var(--accent)';
                      }}
                      onBlur={(e) => {
                        e.target.style.borderColor = 'var(--border)';
                      }}
                    />
                  </div>
                ))
              )}
            </div>

            <div
              style={{
                background: 'rgba(99, 102, 241, 0.1)',
                border: '1px solid rgba(99, 102, 241, 0.3)',
                borderRadius: '8px',
                padding: '16px',
                fontSize: '12px',
                lineHeight: '1.6',
                color: 'var(--text-primary)',
              }}
            >
              <div style={{ fontWeight: 600, marginBottom: '8px' }}>
                💡 What's included:
              </div>
              <ul style={{ margin: 0, paddingLeft: '20px' }}>
                <li>Production-ready Python code</li>
                <li>.env file with your API keys</li>
                <li>requirements.txt for dependencies</li>
                <li>README with setup instructions</li>
              </ul>
            </div>
          </div>

          {/* Footer */}
          <div
            style={{
              padding: '24px',
              borderTop: '1px solid var(--border)',
            }}
          >
            <button
              onClick={handleDownload}
              disabled={isLoading}
              style={{
                width: '100%',
                height: '52px',
                background: isLoading ? 'var(--accent)' : 'linear-gradient(135deg, var(--accent), #8b5cf6)',
                border: 'none',
                borderRadius: '10px',
                color: 'white',
                fontSize: '15px',
                fontWeight: 700,
                cursor: isLoading ? 'not-allowed' : 'pointer',
                opacity: isLoading ? 0.6 : 1,
                fontFamily: 'JetBrains Mono, monospace',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '10px',
                transition: 'all 0.3s ease',
                boxShadow: isLoading
                  ? 'none'
                  : '0 4px 20px rgba(99, 102, 241, 0.4), 0 0 40px rgba(139, 92, 246, 0.3)',
                animation: isLoading ? 'none' : 'pulse-glow 2s ease-in-out infinite',
                letterSpacing: '0.03em',
              }}
              onMouseEnter={(e) => {
                if (!isLoading) {
                  e.currentTarget.style.transform = 'translateY(-2px)';
                  e.currentTarget.style.boxShadow = '0 6px 30px rgba(99, 102, 241, 0.6), 0 0 60px rgba(139, 92, 246, 0.4)';
                }
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = '0 4px 20px rgba(99, 102, 241, 0.4), 0 0 40px rgba(139, 92, 246, 0.3)';
              }}
            >
              <span style={{ fontSize: '18px' }}>📦</span>
              <span>Download Project</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
