import { Router, Request, Response } from 'express';
import { askClaude } from '../lib/claude';
import { SchemaValidator } from '../engine/SchemaValidator';
import type { PipelineSchema, EngineNode, EngineEdge } from '../types/engine';

const router = Router();

// ── Static file templates ─────────────────────────────────────────────────────

function buildRunPy(): string {
  return `import json
import os
import sys
from forge_runner import PipelineRunner

with open('pipeline.json') as f:
    pipeline = json.load(f)

user_input = sys.argv[1] if len(sys.argv) > 1 else input("Enter input: ")
runner = PipelineRunner(pipeline, api_key=os.getenv("ANTHROPIC_API_KEY"))
result = runner.run(user_input)
print(result['finalOutput'])
`;
}

function buildReadme(name: string, nodes: EngineNode[]): string {
  const nodeList = nodes
    .map((n) => {
      const typeLabels: Record<string, string> = {
        input: 'Input — entry point for user data',
        llm: 'LLM — calls an AI language model',
        tool: 'Tool — runs an external tool or API',
        agent: 'Agent — autonomous reasoning loop',
        router: 'Router — routes data based on conditions',
        output: 'Output — final result of the pipeline',
      };
      return `- **${n.id}** (${n.type}): ${typeLabels[n.type] ?? n.type}`;
    })
    .join('\n');

  return `# ${name}

## Setup

\`\`\`bash
pip install anthropic
export ANTHROPIC_API_KEY=your_key_here
\`\`\`

## Run

\`\`\`bash
python run.py 'your input here'
\`\`\`

## Pipeline Structure

${nodeList}

## Generated with Forge ⚡

Build multi-LLM pipelines visually and ship them as real code.
`;
}

const FORGE_RUNNER_SYSTEM = `You are an expert Python developer. Write clean, well-commented, production-quality code.`;

function buildForgeRunnerPrompt(schema: string): string {
  return `Write a self-contained Python class called PipelineRunner that takes a pipeline dict \
matching this schema and an api_key string. It must implement a run(input: str) method that \
executes nodes in topological order, calls the Anthropic API for LLM nodes using the anthropic \
Python SDK, and returns a dict with finalOutput and steps. No external dependencies except \
anthropic and standard library.

Schema:
${schema}

Requirements:
- Use only the anthropic package and Python standard library
- Implement Kahn's algorithm for topological sort
- For 'input' nodes: pass input through unchanged
- For 'llm' nodes: call anthropic.Anthropic(api_key=api_key).messages.create() with the node's config
- For 'tool', 'agent', 'router', 'output' nodes: pass value through with a comment stub
- Return dict with keys: finalOutput (str), steps (list of dicts with nodeId, status, output)
- Handle errors gracefully — if a node fails, add error info to steps and stop execution
- No markdown, no backticks, return ONLY valid Python code`;
}

// ── Route ─────────────────────────────────────────────────────────────────────

router.post('/', async (req: Request, res: Response): Promise<void> => {
  const { nodes, edges, name } = req.body as {
    nodes: EngineNode[];
    edges: EngineEdge[];
    name?: string;
  };

  if (!nodes || !edges) {
    res.status(400).json({ error: 'nodes and edges are required' });
    return;
  }

  const pipelineName = name ?? 'My Pipeline';

  // Build and validate schema
  const pipeline: PipelineSchema = {
    pipeline_version: '1.0',
    id: 'export',
    name: pipelineName,
    created_at: new Date().toISOString(),
    nodes,
    edges,
  };

  const validation = SchemaValidator.validate(pipeline);
  if (!validation.valid) {
    res.status(400).json({ errors: validation.errors });
    return;
  }
  // CHANGE THIS: capture warnings so we can forward them to the frontend
  const exportWarnings: string[] = validation.warnings;

  try {
    // File 1: pipeline.json
    const pipelineJson = JSON.stringify(pipeline, null, 2);

    // File 2: run.py (static template — never generated by Claude)
    const runPy = buildRunPy();

    // File 3: forge_runner.py (generated by Claude once per export)
    const schemaDescription = JSON.stringify(
      {
        pipeline_version: 'string',
        id: 'string',
        name: 'string',
        nodes: '[{ id, type, position, config, inputs, outputs }]',
        edges: '[{ id, source, target }]',
      },
      null,
      2
    );
    const forgeRunnerPy = await askClaude(
      FORGE_RUNNER_SYSTEM,
      buildForgeRunnerPrompt(schemaDescription)
    );

    // File 4: README.md (static template)
    const readme = buildReadme(pipelineName, nodes);

    // CHANGE THIS: include warnings so the frontend can display them
    res.json({
      files: [
        { name: 'pipeline.json', content: pipelineJson, encoding: 'utf8' },
        { name: 'run.py', content: runPy, encoding: 'utf8' },
        { name: 'forge_runner.py', content: forgeRunnerPy, encoding: 'utf8' },
        { name: 'README.md', content: readme, encoding: 'utf8' },
      ],
      warnings: exportWarnings,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    res.status(500).json({ error: message });
  }
});

export default router;
