import type { Node, Edge } from '@xyflow/react';
import type { NodeData } from '../store/pipelineStore';

export const mockGeneratePipeline = (_intent: string) => {
  // Simulate API delay for realistic demo feel
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        nodes: [
          {
            id: 'n1',
            type: 'input',
            position: { x: 100, y: 300 },
            data: { label: 'User Query', status: 'idle' },
            config: {},
          },
          {
            id: 'n2',
            type: 'tool',
            position: { x: 350, y: 200 },
            data: { label: 'Web Search', status: 'idle' },
            config: { toolType: 'web_search' },
          },
          {
            id: 'n3',
            type: 'llm',
            position: { x: 600, y: 300 },
            data: { label: 'Claude Analyzer', status: 'idle' },
            config: {
              model: 'claude-sonnet-4-20250514',
              systemPrompt: 'You are an expert analyst. Synthesize the search results into a comprehensive, actionable response.',
              temperature: 0.7,
            },
          },
          {
            id: 'n4',
            type: 'output',
            position: { x: 850, y: 300 },
            data: { label: 'Final Response', status: 'idle' },
            config: {},
          },
        ] as Node<NodeData>[],
        edges: [
          { id: 'e1', source: 'n1', target: 'n2' },
          { id: 'e2', source: 'n2', target: 'n3' },
          { id: 'e3', source: 'n3', target: 'n4' },
        ] as Edge[],
        copilotMessage: "Pipeline generated! I've set up a search-augmented Claude pipeline. The Web Search node will find relevant information, then Claude will synthesize it into a response. Click any node to configure it.",
      });
    }, 1500);
  });
};

export const mockValidateConnection = (sourceType: string, targetType: string) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        compatible: true,
        message: `✓ ${sourceType} → ${targetType} connection looks perfect! Data will flow smoothly.`,
      });
    }, 300);
  });
};

export const mockGenerateCode = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        code: `import os
import anthropic

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

def run_pipeline(user_input: str) -> str:
    """
    Forge Pipeline: Search-Augmented Claude
    Generated by Forge — forge.ai
    """
    # Step 1: Web Search
    search_results = web_search(user_input)

    # Step 2: Claude Analysis
    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1024,
        system="You are an expert analyst. Synthesize search results into actionable responses.",
        messages=[{
            "role": "user",
            "content": f"Query: {user_input}\\n\\nSearch Results: {search_results}"
        }]
    )

    return message.content[0].text

def web_search(query: str) -> str:
    # Connect your search API here (Serper, Tavily, etc.)
    return f"Search results for: {query}"

if __name__ == "__main__":
    result = run_pipeline("What are the latest AI trends?")
    print(result)`,
        requiredKeys: ['ANTHROPIC_API_KEY'],
      });
    }, 2000);
  });
};

export const mockTestRun = (_pipeline: any, input: string) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        logs: [
          {
            nodeId: 'node_1',
            nodeName: 'User Input',
            status: 'done',
            output: input,
            timestamp: Date.now(),
          },
          {
            nodeId: 'node_2',
            nodeName: 'Claude',
            status: 'running',
            output: 'Processing...',
            timestamp: Date.now() + 1000,
          },
          {
            nodeId: 'node_2',
            nodeName: 'Claude',
            status: 'done',
            output: 'Hello! I can help you with various tasks...',
            timestamp: Date.now() + 3000,
          },
          {
            nodeId: 'node_3',
            nodeName: 'Response',
            status: 'done',
            output: 'Pipeline completed successfully',
            timestamp: Date.now() + 3500,
          },
        ],
      });
    }, 500);
  });
};

export const mockInterpretSketch = (_imageBase64: string, feedback?: string) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        interpretation: feedback
          ? `Refined based on feedback "${feedback}": A pipeline with an input node connected to a Claude LLM node, which routes through a router and feeds into an output node.`
          : 'A pipeline with an input node connected to a Claude LLM node, which feeds into an output node.',
        nodes: [
          {
            id: 'node_1',
            type: 'input',
            position: { x: 100, y: 300 },
            data: { label: 'Input', status: 'idle' },
          },
          {
            id: 'node_2',
            type: 'llm',
            position: { x: 350, y: 300 },
            data: {
              label: 'LLM',
              model: 'claude-sonnet',
              systemPrompt: 'You are a helpful assistant.',
              temperature: 0.7,
              status: 'idle',
            },
          },
          {
            id: 'node_3',
            type: 'output',
            position: { x: 600, y: 300 },
            data: { label: 'Output', status: 'idle' },
          },
        ] as Node<NodeData>[],
        edges: [
          { id: 'e1-2', source: 'node_1', target: 'node_2' },
          { id: 'e2-3', source: 'node_2', target: 'node_3' },
        ] as Edge[],
      });
    }, 1800);
  });
};

/**
 * Copilot message - calls REAL Claude API when in mock mode
 * This ensures the copilot gives intelligent answers during demos
 */
export const mockCopilotMessage = async (
  userMessage: string,
  pipeline: { nodes: any[]; edges: any[] }
): Promise<{ response: string }> => {
  const apiKey = import.meta.env.VITE_ANTHROPIC_API_KEY;

  if (!apiKey || apiKey === 'sk-ant-api03-your-key-here') {
    // Fallback if no API key configured
    return {
      response: `I can help you with that! You have ${pipeline.nodes.length} nodes and ${pipeline.edges.length} connections in your pipeline. Try configuring the nodes or connecting them differently.`,
    };
  }

  try {
    // Call the REAL Anthropic API (using Haiku for fast, cheap responses)
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 500,
        temperature: 0.7,
        system: `You are Forge Copilot, an AI assistant helping users build AI pipelines visually. Be helpful, concise, and specific about pipeline architecture.
Current pipeline context: ${pipeline.nodes.length} nodes (${pipeline.nodes.map((n: any) => n.type).join(', ')}) with ${pipeline.edges.length} connections.`,
        messages: [
          {
            role: 'user',
            content: userMessage,
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`Claude API error: ${response.status}`);
    }

    const data = await response.json();
    return {
      response: data.content[0].text,
    };
  } catch (error) {
    console.error('[mockCopilotMessage] Error calling Claude API:', error);
    return {
      response: `I'm having trouble connecting right now, but here's my take: With ${pipeline.nodes.length} nodes in your pipeline, focus on ensuring each node is properly configured and the data flows logically from input to output.`,
    };
  }
};

export const mockLoadTemplate = (templateName: string) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const templates: Record<string, any> = {
        'research-report': {
          nodes: [
            {
              id: 't1',
              type: 'input',
              position: { x: 100, y: 300 },
              data: { label: 'Research Topic', status: 'idle' },
              config: {},
            },
            {
              id: 't2',
              type: 'tool',
              position: { x: 350, y: 300 },
              data: { label: 'Web Search', status: 'idle' },
              config: { toolType: 'web_search' },
            },
            {
              id: 't3',
              type: 'llm',
              position: { x: 600, y: 300 },
              data: { label: 'Claude Synthesizer', status: 'idle' },
              config: {
                model: 'claude-sonnet-4-20250514',
                systemPrompt: 'You are a research assistant. Synthesize the search results into a comprehensive, well-structured report.',
                temperature: 0.5,
              },
            },
            {
              id: 't4',
              type: 'output',
              position: { x: 850, y: 300 },
              data: { label: 'Report', status: 'idle' },
              config: {},
            },
          ],
          edges: [
            { id: 'e1-2', source: 't1', target: 't2' },
            { id: 'e2-3', source: 't2', target: 't3' },
            { id: 'e3-4', source: 't3', target: 't4' },
          ],
          copilotMessage: 'Research & Report loaded! Enter any topic and this pipeline will search the web and generate a comprehensive report.',
        },
        'support-bot': {
          nodes: [
            {
              id: 's1',
              type: 'input',
              position: { x: 100, y: 300 },
              data: { label: 'Customer Message', status: 'idle' },
              config: {},
            },
            {
              id: 's2',
              type: 'llm',
              position: { x: 400, y: 300 },
              data: { label: 'Support Agent', status: 'idle' },
              config: {
                model: 'claude-sonnet-4-20250514',
                systemPrompt: 'You are a helpful customer support agent. Handle inquiries with empathy and accuracy.',
                temperature: 0.3,
              },
            },
            {
              id: 's3',
              type: 'output',
              position: { x: 700, y: 300 },
              data: { label: 'Response', status: 'idle' },
              config: {},
            },
          ],
          edges: [
            { id: 'e1-2', source: 's1', target: 's2' },
            { id: 'e2-3', source: 's2', target: 's3' },
          ],
          copilotMessage: 'Support Bot loaded! This pipeline uses Claude to handle customer inquiries with empathy and accuracy.',
        },
        'code-reviewer': {
          nodes: [
            {
              id: 'c1',
              type: 'input',
              position: { x: 100, y: 300 },
              data: { label: 'Code', status: 'idle' },
              config: {},
            },
            {
              id: 'c2',
              type: 'llm',
              position: { x: 300, y: 200 },
              data: { label: 'Bug Finder', status: 'idle' },
              config: {
                model: 'claude-sonnet-4-20250514',
                systemPrompt: 'You are a code reviewer focused on finding bugs and logic errors.',
                temperature: 0.4,
              },
            },
            {
              id: 'c3',
              type: 'llm',
              position: { x: 300, y: 400 },
              data: { label: 'Style Checker', status: 'idle' },
              config: {
                model: 'claude-sonnet-4-20250514',
                systemPrompt: 'You are a code reviewer focused on style and best practices.',
                temperature: 0.4,
              },
            },
            {
              id: 'c4',
              type: 'llm',
              position: { x: 550, y: 300 },
              data: { label: 'Report Writer', status: 'idle' },
              config: {
                model: 'claude-sonnet-4-20250514',
                systemPrompt: 'You are a code reviewer. Combine feedback from bug and style analysis into a comprehensive review.',
                temperature: 0.4,
              },
            },
            {
              id: 'c5',
              type: 'output',
              position: { x: 800, y: 300 },
              data: { label: 'Review', status: 'idle' },
              config: {},
            },
          ],
          edges: [
            { id: 'e1-2', source: 'c1', target: 'c2' },
            { id: 'e1-3', source: 'c1', target: 'c3' },
            { id: 'e2-4', source: 'c2', target: 'c4' },
            { id: 'e3-4', source: 'c3', target: 'c4' },
            { id: 'e4-5', source: 'c4', target: 'c5' },
          ],
          copilotMessage: 'Code Reviewer loaded! Two specialized Claude agents review your code in parallel, then combine their findings.',
        },
      };

      const template = templates[templateName] || templates['research-report'];
      resolve(template);
    }, 800);
  });
};
